version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout       
      - run:
          name: Restore NuGets from two feeds
          command: dotnet restore -s ${myget_feed} -s https://api.nuget.org/v3/index.json -s https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
      - run:
          name: Build
          command: dotnet build
